.sco-so-api-deployment: &sco-so-api-deployment
  - cd deploy && ./docker-deploy.sh -s api

sco-so-api-check-status:
  before_script:
    - *sco-so-api-deployment
  script:
    - curl -Is http://127.0.0.1:50101/api/docs | head -n 1
  tags: [sco-so-api]
