.sco-so-mon-deployment: &sco-so-mon-deployment
  - cd deploy && ./docker-deploy.sh -s mon

sco-so-mon-check-status:
  before_script:
    - *sco-so-mon-deployment
  script:
    - curl -Is http://127.0.0.1:50104/status | head -n 1
  tags: [sco-so-mon]
