version: "3.8"

services:
  so_dbl:
    image: mongo:4.2.23
    container_name: so-${SO_MODL_NAME}
    hostname: ${SO_MODL_NAME}
    restart: unless-stopped
    command: --port ${SO_MODL_API_PORT}
    environment:
      - SO_MODL_NAME
      - SO_MODL_API_PORT
      # https://hub.docker.com/_/mongo
      - MONGO_INITDB_ROOT_USERNAME=${SO_MODL_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SO_MODL_DB_USERPASSWORD}
    ports:
      - "${SO_MODL_API_PORT}:${SO_MODL_API_PORT}"
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongo so_${SO_MODL_NAME}:${SO_MODL_API_PORT}/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - so-dbl:/data/db
    # Bind-mount version (not preferred by Docker - might be corrupted easily)
    #volumes:
    #  - ${PWD}/../../data:/data/db
    networks:
      - so-db

networks:
  so-db:
    driver: bridge
    external: true
volumes:
  so-dbl:
