version: "3.8"

services:
  so_db:
    image: mongo
    container_name: ${SO_MODL_NAME}
    hostname: ${SO_MODL_NAME}
    restart: unless-stopped
    #environment:
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:50103"
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongo so-db:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    # TODO: use a volume rather than a bind-mount
    volumes:
      - ${PWD}/../../data:/data/db
    networks:
      - so-db

networks:
  so-db:
    driver: bridge
    external: true
