version: "3.8"

services:
  so_dbl:
    image: mongo
    container_name: so-${SO_MODL_NAME}
    hostname: ${SO_MODL_NAME}
    restart: unless-stopped
    command: --port ${SO_MODL_API_PORT}
    environment:
      - SO_MODL_NAME
      - SO_MODL_API_PORT
    #  - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${SO_MODL_API_PORT}:${SO_MODL_API_PORT}"
    healthcheck:
      test: echo "db.runCommand('ping').ok" | mongo so_${SO_MODL_NAME}:${SO_MODL_API_PORT}/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    # TODO: use a volume rather than a bind-mount
    volumes:
      - ${PWD}/../../data:/data/db
    networks:
      - so-db

networks:
  so-db:
    driver: bridge
    external: true
